In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is Available")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not availalbe")
    

GPU is Available
Using GPU:Tesla P100-PCIE-16GB


# Creating a tensor

In [4]:
# using empty
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
a= torch.empty(3,3)

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# Using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.6268, 0.0756, 0.5805],
        [0.1469, 0.4333, 0.2441]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye Identity Matrix
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [14]:
a.shape

torch.Size([3, 3])

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
# copy the shape
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068654568117382454, 3617580396540737329, 6499034239897579822]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Type

In [21]:
# find data type
x.dtype

torch.int64

In [22]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# using to() Changeing Datatype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathemathical Operations

# 1.Scalar Operation

In [25]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# 2. Element wise operation

In [27]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [28]:
# add
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [29]:
# sub
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [30]:
# multiply
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [31]:
# division
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [32]:
# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [33]:
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [34]:
c = torch.tensor([1, -2, 3, -4])

In [35]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [36]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [37]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [38]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [39]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [40]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

# Range

In [41]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction Operation

In [42]:
e= torch.randint(size=(2,3),low=0,high=10)
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [43]:
#sum
torch.sum(e)

tensor(24)

In [44]:
# sum column wise
torch.sum(e,dim=0)

tensor([ 8,  0, 16])

In [45]:
# sum row wise
torch.sum(e,dim=1)

tensor([15,  9])

In [46]:
# mean
e= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
torch.mean(e)

tensor(4.6667)

In [47]:
# median
torch.median(e)

tensor(4.)

In [48]:
torch.max(e)
torch.min(e)

tensor(0.)

In [49]:
torch.prod(e)

tensor(0.)

In [50]:
torch.std(e)

tensor(3.1411)

In [51]:
torch.var(e)

tensor(9.8667)

In [52]:
torch.argmax(e)

tensor(3)

In [53]:
torch.argmin(e)

tensor(5)

# Matrix operations

In [54]:
f= torch.randint(size=(2,3),low=0,high=10)
g= torch.randint(size=(3,2),low=0,high=12)

In [55]:
# Matrix Multiplication
torch.matmul(f,g)

tensor([[ 62, 109],
        [ 84, 165]])

In [56]:
vector1= torch.tensor([1,2])
vector2= torch.tensor([3,4])
# Dot product
torch.dot(vector1,vector2)

tensor(11)

In [57]:
# Transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [58]:
h= torch.randint(size=(3,3),low=1,high=14,dtype=torch.float32)
h

tensor([[13.,  6.,  1.],
        [ 6.,  3., 10.],
        [ 3.,  1., 10.]])

In [59]:
# Determinant
torch.det(h)

tensor(77.0000)

In [60]:
# Inverse
torch.inverse(h)

tensor([[ 0.2597, -0.7662,  0.7403],
        [-0.3896,  1.6494, -1.6104],
        [-0.0390,  0.0649,  0.0390]])

# Comparision operations

In [61]:
i =torch.randint(size=(2,3),low=1,high=12)
j= torch.randint(size=(2,3),low=3,high=9)
print(i)
print(j)

tensor([[ 1,  9,  5],
        [ 5,  7, 11]])
tensor([[8, 4, 6],
        [3, 5, 3]])


In [62]:
# Greater than 
i>j

tensor([[False,  True, False],
        [ True,  True,  True]])

In [63]:
# less than 
i<j

tensor([[ True, False,  True],
        [False, False, False]])

In [64]:
# Equal
i==j

tensor([[False, False, False],
        [False, False, False]])

# SPecial Operation

In [65]:
k= torch.randint(size=(2,3),low=0,high=10)
k

tensor([[0, 8, 4],
        [7, 2, 3]])

In [66]:
# Log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [67]:
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [68]:
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [69]:
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [70]:
k= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
torch.softmax(k,dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [71]:
# Relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

# Inplace Operations ; permanent changes implement

In [72]:
m= torch.rand(2,3)
n= torch.rand(2,3)
print(m)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [73]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [74]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [75]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

# Tensor operation on GPU

In [76]:
torch.cuda.is_available()

True

In [77]:
device = torch.device('cuda')

In [78]:
# Creating a New Tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [79]:
# Moving exisiting tensor to GPU
b=a.to(device)

In [80]:
b

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]], device='cuda:0')

# Tensor torch multiplication

In [81]:
# File: cpu_vs_gpu_matrix_multiplication.py

# Line 1
import torch

# Line 2
import time

# Line 3
# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Line 4
# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)

# Line 5
matrix_cpu2 = torch.randn(size, size)

# Line 6
# Measure time on CPU
start_time = time.time()

# Line 7
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU

# Line 8
cpu_time = time.time() - start_time

# Line 9
print(f"Time on CPU: {cpu_time:.4f} seconds")

# Line 10
# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')

# Line 11
matrix_gpu2 = matrix_cpu2.to('cuda')

# Line 12
# Measure time on GPU
start_time = time.time()

# Line 13
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU

# Line 14
torch.cuda.synchronize()  # Ensure all GPU operations are complete

# Line 15
gpu_time = time.time() - start_time

# Line 16
print(f"Time on GPU: {gpu_time:.4f} seconds")

Time on CPU: 7.4524 seconds
Time on GPU: 0.3160 seconds


In [82]:
# Reshaping Tensors
a =torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [84]:
# Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
# Permute
b = torch.rand(2,3,4)
b

tensor([[[0.8881, 0.7989, 0.9514, 0.0141],
         [0.8903, 0.1649, 0.3162, 0.1331],
         [0.6763, 0.4254, 0.2375, 0.5430]],

        [[0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009],
         [0.5839, 0.0061, 0.4671, 0.8243]]])

In [86]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [87]:
# Unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [88]:
# Squeeze
d= torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# NUMPY AND PYTORCH

In [89]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [90]:
b= a.numpy()

In [91]:
b

array([1, 2, 3])

In [92]:
type(b)

numpy.ndarray

In [93]:
c= np.array([1,2,3,4])

In [94]:
torch.from_numpy(c)

tensor([1, 2, 3, 4])